<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260419092935 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE game_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_id VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1912E4FF7E3C61F9 ON game_entry (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_owner_provider_game ON game_entry (provider_id, owner_id)');
        $this->addSql('CREATE TABLE manga_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_id VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BD7761177E3C61F9 ON manga_entry (owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_owner_provider_manga ON manga_entry (owner_id, provider_id)');
        $this->addSql('ALTER TABLE game_entry ADD CONSTRAINT FK_1912E4FF7E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE manga_entry ADD CONSTRAINT FK_BD7761177E3C61F9 FOREIGN KEY (owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE game_entry DROP CONSTRAINT FK_1912E4FF7E3C61F9');
        $this->addSql('ALTER TABLE manga_entry DROP CONSTRAINT FK_BD7761177E3C61F9');
        $this->addSql('DROP TABLE game_entry');
        $this->addSql('DROP TABLE manga_entry');
    }
}
